#ifndef __CONFIG_H__
#define __CONFIG_H__

#define GTK_THEME_DIR "@GTK_THEME_DIR@/gtk-2.0"
#ifndef OXYGEN_DEBUG
#   define OXYGEN_DEBUG @OXYGEN_DEBUG@
#endif
#define OXYGEN_ICON_HACK @OXYGEN_ICON_HACK@
#define ENABLE_COMBOBOX_LIST_RESIZE @ENABLE_COMBOBOX_LIST_RESIZE@

#endif
